import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { spawnSync } from 'node:child_process';
import { fileURLToPath, pathToFileURL } from 'node:url';
import crypto from 'node:crypto';
const workspace=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const sourceIndex=process.argv.indexOf('--source');
const project=sourceIndex>=0?path.resolve(process.argv[sourceIndex+1]):workspace;
const fixture=fs.mkdtempSync(path.join(os.tmpdir(),'sgs-new-user-'));
const home=path.join(fixture,'HOME with spaces');fs.mkdirSync(home,{recursive:true});
const env={...process.env,HOME:home,USERPROFILE:home,SGS_CONFIG:''};
const output=path.join(workspace,'outputs/runs');fs.mkdirSync(output,{recursive:true});
const mode=process.argv.includes('--baseline')?'baseline':'regression';
const json=(file,value)=>{fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify(value,null,2));};
const profile=(name,patch={})=>{const p=path.join(fixture,name,'profile with spaces.json');json(p,{schema:'sgs/runtime-profile@1',profile_name:'test',discovery_roots:[path.join(home,'.codex/skills'),path.join(home,'.agents/skills')],cold_store:path.join(home,'cold'),authorization_directory:path.join(home,'auth'),host_binding:null,production_writes_enabled:false,native_desktop:'UNKNOWN',artifacts:{},candidates:{},...patch});return p;};
for(const root of ['.codex/skills','.agents/skills','.codex/skills/.system'])fs.mkdirSync(path.join(home,root),{recursive:true});
for(const [name,root,text]of [['alpha','.codex/skills','alpha'],['beta','.agents/skills','beta'],['duplicate-a','.codex/skills','duplicate'],['duplicate-b','.agents/skills','duplicate'],['managed','.codex/skills/.system','managed']]){const f=path.join(home,root,name,'SKILL.md');fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,`---\nname: ${text}\ndescription: isolated fixture\n---\nHarmless instruction only.\n`);}
const config=profile('normal');
function run(args,{cwd=project,extraEnv={},prefix=[]}={}){const r=spawnSync(process.execPath,[...prefix,'src/sgs.mjs',...args],{cwd,env:{...env,...extraEnv},encoding:'utf8',timeout:30000});let data;try{data=JSON.parse(r.stdout.replace(/^\uFEFF/,''));}catch{}return{exit:r.status,stdout:r.stdout,stderr:r.stderr,data};}
function tool(file,args=[],options={}){const r=spawnSync(process.execPath,[...(options.prefix||[]),file,...args],{cwd:project,env,encoding:'utf8',timeout:30000});return {exit:r.status,stdout:r.stdout,stderr:r.stderr};}
const rows=[];
async function check(id,issue,expected,fn,kind='CONFIRMED'){let actual,pass=false,error;try{actual=await fn();pass=true;}catch(e){actual=e.actual;error=e.message;}rows.push({id:`BUG-${String(id).padStart(2,'0')}`,reported_issue:issue,reproduced:mode==='baseline'?!pass:null,reproduction_command:`node test/new-user-deployment.test.mjs ${mode==='baseline'?'--baseline':''}${sourceIndex>=0?' --source "'+project+'"':''}`,expected,actual:actual??{error},severity:[7,10,14,15,16,17,19].includes(id)?'P1':'P2',fix_required:mode==='baseline'?!pass:true,test_file:'test/new-user-deployment.test.mjs',status:mode==='baseline'?(pass?'NOT_REPRODUCED':kind):(pass?'FIXED':'CONFIRMED'),pass});}
function expect(result,predicate){if(!predicate(result)){const e=new Error('Expected behavior not observed');e.actual=result;throw e;}return result;}
const entry=path.join(home,'.codex/skills/skill-governance');
await check(1,'No formal entry install','install-entry creates thin entry',()=>expect(run(['--config',config,'install-entry','--root',path.dirname(entry)]),r=>r.exit===0&&fs.existsSync(path.join(entry,'SKILL.md'))),'UX_GAP');
await check(2,'Moving project leaves old pointer','rebind-entry updates pointer and retains backup',()=>{json(path.join(entry,'references/runtime.json'),{schema:'sgs/skill-runtime-pointer@1',project_root:path.join(fixture,'old project'),entry:'src/sgs.mjs',node_command:process.execPath});const r=run(['--config',config,'rebind-entry','--entry',entry,'--project',project]);return expect(r,r=>r.exit===0&&fs.existsSync(r.data?.backup_path||''));},'UX_GAP');
await check(3,'Entry Node executable not resolved','render pointer uses existing absolute executable',()=>{const out=path.join(fixture,'node-entry');const r=tool('tools/render-skill-entry.mjs',['--out',out]);return expect(r,r=>r.exit===0&&path.isAbsolute(JSON.parse(fs.readFileSync(path.join(out,'references/runtime.json'),'utf8')).node_command));},'ENVIRONMENT_DEPENDENT');
await check(4,'Custom config lost in pointer','config_path preserved',()=>{const out=path.join(fixture,'config-entry');const r=tool('tools/render-skill-entry.mjs',['--out',out,'--config',config]);return expect(r,r=>r.exit===0&&JSON.parse(fs.readFileSync(path.join(out,'references/runtime.json'),'utf8')).config_path===config);},'UX_GAP');
const injection=path.join(fixture,'failure.mjs');fs.writeFileSync(injection,`import fs from 'node:fs';import{syncBuiltinESMExports}from'node:module';const write=fs.writeFileSync;const copy=fs.copyFileSync;let n=0;fs.writeFileSync=(p,...a)=>{if(String(p).includes('runtime.json'))throw new Error('INJECTED_WRITE_FAILURE');return write(p,...a)};fs.copyFileSync=(...a)=>{if(++n===3)throw new Error('INJECTED_COPY_FAILURE');return copy(...a)};syncBuiltinESMExports();`);
await check(5,'Entry partial failure leaves target','injected failure reached; no final target or owned temp',()=>{const out=path.join(fixture,'partial-entry');const r=tool('tools/render-skill-entry.mjs',['--out',out],{prefix:['--import',pathToFileURL(injection).href]});return expect(r,r=>r.stderr.includes('INJECTED_WRITE_FAILURE')&&r.exit!==0&&!fs.existsSync(out)&&!fs.readdirSync(fixture).some(n=>n.startsWith('partial-entry.tmp-')));},'ENVIRONMENT_DEPENDENT');
await check(6,'Export partial failure leaves target','injected failure reached; no final target or owned temp',()=>{const out=path.join(fixture,'partial-export');const r=tool('tools/export-portable.mjs',['--out',out],{prefix:['--import',pathToFileURL(injection).href]});return expect(r,r=>r.stderr.includes('INJECTED_COPY_FAILURE')&&r.exit!==0&&!fs.existsSync(out)&&!fs.readdirSync(fixture).some(n=>n.startsWith('partial-export.tmp-')));},'ENVIRONMENT_DEPENDENT');
await check(7,'Explicit missing config falls back','CONFIG_NOT_FOUND for flag and environment',()=>{const file=path.join(fixture,'missing.json');const a=run(['--config',file,'status']),b=run(['status'],{extraEnv:{SGS_CONFIG:file}});return expect({a,b},r=>r.a.exit!==0&&r.b.exit!==0&&r.a.stderr.includes('CONFIG_NOT_FOUND')&&r.b.stderr.includes('CONFIG_NOT_FOUND'));});
await check(8,'init does not create config parent','init creates missing parent without overwriting',()=>{const p=path.join(fixture,'new parent','p.json');const a=run(['--config',p,'init']),b=run(['--config',p,'init']);return expect({a,b},r=>r.a.exit===0&&r.b.exit!==0&&fs.existsSync(p));});
await check(9,'Profile fields poorly validated','field-specific INVALID_PROFILE_FIELD',()=>{const p=profile('bad-fields',{artifacts:[]});return expect(run(['--config',p,'status']),r=>r.exit!==0&&r.stderr.includes('INVALID_PROFILE_FIELD')&&r.stderr.includes('artifacts'));});
const capability=path.join(fixture,'broken-capability.json');fs.writeFileSync(capability,'{bad');
const badConfig=profile('bad-capability',{artifacts:{filesystem_capability:capability}});
let d=run(['--config',badConfig,'doctor']);let p=JSON.parse(fs.readFileSync(badConfig));p.host_binding=d.data?.host_key??'unknown';json(badConfig,p);
await check(10,'Bad capability kills doctor','doctor returns invalid_json; status fails closed',()=>{const a=run(['--config',badConfig,'doctor']),b=run(['--config',badConfig,'status']);return expect({a,b},r=>r.a.exit===0&&r.a.data.artifacts.filesystem_capability.valid_json===false&&r.b.exit!==0);});
await check(11,'BOM scan/dry-run JSON','both commands accept BOM',()=>{const scope=path.join(fixture,'bom.json'),out=path.join(fixture,'scan.json');fs.writeFileSync(scope,'\uFEFF'+JSON.stringify({roots:[{id:'user',kind:'USER_SKILLS',path:path.join(home,'.agents/skills')}]}));const a=tool('src/scan.mjs',['--scope',scope,'--out',out]);if(fs.existsSync(out))fs.writeFileSync(out,'\uFEFF'+fs.readFileSync(out,'utf8'));const b=tool('src/profile-dry-run.mjs',['--scan',out,'--out',path.join(fixture,'dry.json')]);return expect({a,b},r=>r.a.exit===0&&r.b.exit===0);});
await check(12,'config equals syntax unsupported','--config=path matches spaced form',()=>expect(run([`--config=${config}`,'status']),r=>r.exit===0&&r.data.runtime.config===config));
await check(13,'Duplicate config not rejected','DUPLICATE_CONFIG_OPTION',()=>expect(run(['--config',config,'--config',config,'status']),r=>r.exit!==0&&r.stderr.includes('DUPLICATE_CONFIG_OPTION')));
await check(14,'Conflicting cleanup operations','all four conflict pairs rejected explicitly',()=>{const pairs=[['--apply','--rollback'],['--safe','--apply'],['--verify','--rollback'],['--apply','--verify']].map(pair=>run(['--config',config,'cleanup',...pair]));return expect(pairs,rs=>rs.every(r=>r.exit!==0&&r.stderr.includes('CONFLICTING_CLEANUP_OPERATION')));});
await check(15,'Missing value consumes flag','BATCH_ID_REQUIRED and duplicate value rejection',()=>expect(run(['--config',config,'cleanup','--apply','--batch','--authorized']),r=>r.exit!==0&&r.stderr.includes('BATCH_ID_REQUIRED')));
await check(16,'Cross-volume cold store not diagnosed','doctor reports volumes and next action',()=>{const p=profile('cross-volume',{cold_store:'Z:\\sgs-isolated-cold'});return expect(run(['--config',p,'doctor']),r=>r.exit===0&&r.data.limitations.includes('CROSS_VOLUME_COLD_STORE')&&r.data.volume_conflicts.length>0&&r.data.next_action.includes('cold_store'));},'ENVIRONMENT_DEPENDENT');
await check(17,'Overlap not diagnosed','doctor reports overlap and exact paths',()=>{const p=profile('overlap',{cold_store:path.join(home,'.codex/skills/cold')});return expect(run(['--config',p,'doctor']),r=>r.exit===0&&r.data.limitations.includes('COLD_STORE_OVERLAPS_DISCOVERY'));});
await check(18,'Artifacts only checked for existence','JSON and schema validation output',()=>{const a=path.join(fixture,'bad-index.json');fs.writeFileSync(a,'{"schema":"wrong"}');const p=profile('artifact',{artifacts:{index:a}});return expect(run(['--config',p,'doctor']),r=>r.exit===0&&r.data.artifacts.index.schema_valid===false&&r.data.limitations.includes('CONFIGURED_ARTIFACT_INVALID'));});
await check(19,'One bad receipt collapses observations','valid rows remain and mutation fails closed',()=>{const cold=path.join(fixture,'corrupt-cold');json(path.join(cold,'changesets/VALID.json'),{id:'VALID',state:'COLD',target:path.join(home,'.agents/skills/beta'),blockers:[]});fs.writeFileSync(path.join(cold,'changesets/BAD.json'),'{bad');fs.mkdirSync(path.join(cold,'batches'),{recursive:true});fs.writeFileSync(path.join(cold,'batches/BATCH-BAD.json'),'{bad');const p=profile('corrupt-receipt',{cold_store:cold});const a=run(['--config',p,'changes']),b=run(['--config',p,'status']),c=run(['--config',p,'rollback','BAD']);return expect({a,b,c},r=>r.a.exit===0&&r.b.exit===0&&r.a.stdout.includes('CORRUPT_RECEIPT')&&r.a.stdout.includes('VALID')&&r.b.stdout.includes('degraded')&&r.c.exit!==0);});
await check(20,'No inventory bootstrap journey','bootstrap makes status index non-null and read-only',()=>{const a=run(['--config',config,'bootstrap']),b=run(['--config',config,'status']);return expect({a,b},r=>r.a.exit===0&&r.b.exit===0&&r.b.data.index!==null&&r.b.data.runtime.production_writes_enabled===false);},'UX_GAP');
const file=path.join(output,mode==='baseline'?'new-user-deployment-bug-matrix-20261005.json':'new-user-deployment-regression-20261005.json');
json(file,{schema:'sgs/deployment-bug-matrix@1',phase:'NEW-USER-DEPLOYMENT-HARDENING',mode,fixture,rows,passed:rows.filter(r=>r.pass).length,total:rows.length});
console.log(JSON.stringify({mode,total:rows.length,passed:rows.filter(r=>r.pass).length,output:file,fixture}));
if(mode==='regression'&&rows.some(r=>!r.pass))process.exitCode=1;
